@startuml
'https://plantuml.com/class-diagram

+class programManager {
+ songs : ArrayList<Song>
+ selectAction(action : int)
+ placeOrder(songNum : int, email : String, cardNum : int, sweetHeartName : String)
+ generateReport(memberID : int)
+ singerCheckOut(memberID : int)
}
+class Song {
    +name : String
    +singerID : int
    -inProgress : bool
    canSing()
}
+class Customer {
- email : String
- cardNum : int
+ sweetHeartName : String
+ songNum : int
+ chargeCard()
}

+enum Action {
ORDER,
REPORT,
DONE
}
programManager --|> Song
programManager ..|> Customer
@enduml