@startuml
'https://plantuml.com/class-diagram

+class ProgramManager {
    - songToSinger: HashMap<String, Singer>
    - singer: HashMap<Integer, Singer>
    + selectAction(action: Action): void
    - placeOrder(songNum: int, email: String, cardNum: int, sweetHeartName: String): boolean
    - generateReport(singerID: int): String
    - singerCheckOut(singerID : int): boolean
}

+class Order {
    - orderID: int
    - customerEmail: String
    - customerCardNum: int
    - sweetheartName: String
    - songOrdered: String
    + getSweetheartName(): String
    + chargeCard(): boolean
}

+class Singer {
    - id: int
    - name: String
    - songName: String
    - singOrders: ArrayList<Order>
    - isAvailable: boolean
    + generateEmailReport(): String
    + addOrder(order: Order): boolean
    + finishOrders(): boolean
}

+enum Action {
    ORDER,
    REPORT,
    DONE,
    SUMMARY
}

ProgramManager .u.> Action
ProgramManager -->"*" Singer
Singer -->"*"Order
@enduml