@startuml
'https://plantuml.com/class-diagram

+class ProgramManager {
    - songToSinger: HashMap<String, Singer>
    - singer: HashMap<Integer, Singer>
    - nextOrderNum: int
    - scanner: Scanner
    - NUM_TRIES_BEFORE_ERROR: int

    + ProgramManager(songToSinger: HashMap<String, Singer>, singer: HashMap<Integer, Singer>)
    + selectAction(action: Action): void
    + getScanner(): Scanner
    - getAction(choice: int): Action
    - getSingerFromInput(): Singer
    - selectSong(): int
    - placeOrder(songNum: int, email: String, cardNum: int, sweetHeartName: String): boolean
    - handleGenerateReport(s: Singer): String
    - handleSingerCheckOut(s: Singer): int
    - checkEmailValidity(email: String): boolean
}

+class Order {
    - orderID: int
    - customerEmail: String
    - customerCardNum: long
    - sweetheartName: String
    - songOrdered: String

    + Order(orderID: int, customerEmail: String, customerCardNum: long, sweetheartName: String, songOrdered: String)
    + getSweetheartName(): String
    + chargeCard(): void
    + toString(): String
}

+class Singer {
    - id: int
    - name: String
    - songName: String
    - singOrders: ArrayList<Order>
    - isAvailable: boolean

    + Singer(id: int, name: String, songName: String)
    + generateEmailReport(): String
    + addOrder(order: Order): boolean
    + finishOrders(): int
    + isAvailable(): boolean
    + getSongName(): String
    + getId(): String
    + getOrderReport(): String
    + toString(): String
}

+enum Action {
    ORDER,
    REPORT,
    DONE,
    SUMMARY
}

ProgramManager .u.> Action
ProgramManager -->"*" Singer
Singer -->"*"Order
@enduml